<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_useremail</name>
   <tag></tag>
   <elementGuidId>efae6c88-c1c9-46b0-a1b2-72bbaf2eba3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#useremail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='useremail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;E-mail&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6e73d97-78e8-4d8e-95df-81280fb93e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>useremail</value>
      <webElementGuid>087fbb4f-8d2d-46d0-ad42-587d20d98d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>useremail</value>
      <webElementGuid>577bfacb-da3b-42cf-8154-34a800179910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>dde42f56-9f55-404e-81ec-a7b72cde34c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;useremail&quot;)</value>
      <webElementGuid>2998b856-0a0d-4b06-943f-9e6b0de9c50d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='useremail']</value>
      <webElementGuid>954b7a3f-2079-4347-aecf-d81e090bd722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='contactInfo']/input</value>
      <webElementGuid>473373fa-4c58-4578-a672-f45b06648304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c0db9493-93cb-4983-bf47-17c5678ae654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'useremail' and @id = 'useremail' and @type = 'email']</value>
      <webElementGuid>ef1e8f74-9458-49d9-a9ce-b670ac0a110e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
