<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_165.00</name>
   <tag></tag>
   <elementGuidId>253aaf8e-685a-497d-84f0-4ca819b6a030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='regTotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#regTotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$165.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2cb098a3-c1ea-4911-b7f9-462ba9e97667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regTotal</value>
      <webElementGuid>b64e9edc-7067-4283-8c8e-7ede166ba771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$165.00</value>
      <webElementGuid>b6980517-2aa9-45da-a57e-c6357b253de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regTotal&quot;)</value>
      <webElementGuid>b1e1450b-ea9b-460f-958a-250792a681a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='regTotal']</value>
      <webElementGuid>d14c5144-02c8-4555-b94c-acd0993dcafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='reg2Aside']/table/tbody/tr[6]/td/span</value>
      <webElementGuid>778e5118-ad14-4570-af0e-c56961824446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/following::span[1]</value>
      <webElementGuid>594e5f48-7621-4a2f-a293-ff6427f6df8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no'])[1]/following::span[1]</value>
      <webElementGuid>58f3b5cb-0fe3-4780-8baf-67dd31b01761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$165.00']/parent::*</value>
      <webElementGuid>ebeec78f-0b51-4c0d-9989-974cf5e96027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/span</value>
      <webElementGuid>1b895689-f316-4f94-addc-33d9ee1cd0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'regTotal' and (text() = '$165.00' or . = '$165.00')]</value>
      <webElementGuid>55864ea4-6e20-46cb-b95a-434e14a26c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
