<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_165.00</name>
   <tag></tag>
   <elementGuidId>a127dc82-9789-46e0-a5bb-7315d28a68e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='regTotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#regTotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$165.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>564caddc-5b90-40df-9fc9-5443bf875ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regTotal</value>
      <webElementGuid>98d65164-3854-4830-a026-8a5b384389ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$165.00</value>
      <webElementGuid>036dad4a-9619-4327-a40d-8971da47ec33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regTotal&quot;)</value>
      <webElementGuid>5576e99e-fa17-4d2f-92af-d9cf468781df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='regTotal']</value>
      <webElementGuid>77bae6bc-3900-44d6-afad-3b1bf1252f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='reg1Aside']/table/tbody/tr[6]/td/span</value>
      <webElementGuid>24327bb7-cbbf-471f-bdb8-26686ab2d2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/following::span[1]</value>
      <webElementGuid>bf385738-138e-493c-b680-f0f88d9ef0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no'])[1]/following::span[1]</value>
      <webElementGuid>a757158b-8c57-4868-aa60-130ab7e7a494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$165.00']/parent::*</value>
      <webElementGuid>369eb83f-0413-47b2-a591-3d7e796e2bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/span</value>
      <webElementGuid>9784ecf8-2ace-43fd-8096-deed4547ee4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'regTotal' and (text() = '$165.00' or . = '$165.00')]</value>
      <webElementGuid>39b8a116-03c8-48f7-9315-d113d624e1e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
