<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_expDate</name>
   <tag></tag>
   <elementGuidId>3973b9d4-7025-43ff-ba56-a27f8ec7ea6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;mm/yyyy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c5e382f-d3eb-4661-8756-36a4eed50016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>9813d9c6-4619-4f5d-a0e9-e3d768af77f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>40004f90-f9ad-42db-8325-ef121b7663e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34af6c48-406f-4c35-a487-e96c111d0a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/yyyy</value>
      <webElementGuid>3c3dd655-1dbc-48eb-8357-71d158289852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expDate&quot;)</value>
      <webElementGuid>9e7e8f9e-76e9-4641-878c-c651ea704c4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expDate']</value>
      <webElementGuid>5457e033-bf6e-4e79-8366-bae29f9d2680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input[3]</value>
      <webElementGuid>10dd7d1e-fd03-4823-8b18-b69089ed28c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>aa2c6b13-ba05-4c24-a00d-1cd7914b84ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'expDate' and @id = 'expDate' and @type = 'text' and @placeholder = 'mm/yyyy']</value>
      <webElementGuid>816c0939-c138-4524-85ff-9c1b1099c387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
