<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Holder_cardHolder</name>
   <tag></tag>
   <elementGuidId>a04c7e34-758d-4347-b094-d866b8eb3151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardHolder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardHolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Card Holder*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c48d13a-20e0-45bc-a35b-5f5992bf8353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>a812b672-efeb-43e3-ba86-e481c05452b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>60fad6ef-fd0b-4ad3-815c-7d6aa8c2a2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8147cc8-957f-4878-a058-35e8671f9860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardHolder&quot;)</value>
      <webElementGuid>be97dd27-0a8d-440c-b9a5-1f58290f90d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardHolder']</value>
      <webElementGuid>a1eab692-6962-4bb6-b6dd-2c70891bcd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input</value>
      <webElementGuid>a10237d0-c4da-48fa-a0ed-7f05eaaafb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>67afdc83-29cf-481e-a364-2307c9270d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardHolder' and @id = 'cardHolder' and @type = 'text']</value>
      <webElementGuid>20717b13-c339-4ff0-b6a7-71237d2161d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
