<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VSLive Media Pack (120)_mediaPack</name>
   <tag></tag>
   <elementGuidId>5de2b6d0-7573-45df-9c30-84a30b71b358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mediaCB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mediaCB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mediaCB</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71d066c3-cfbb-4411-bd43-600bbff21252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>22c52931-bd7a-4499-a12d-6f25f5ba3b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mediaPack</value>
      <webElementGuid>7f2ebd22-9c9c-4511-aa23-7c16d37bea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mediaCB</value>
      <webElementGuid>3e4a23a7-c6ec-434d-b3bd-784cab38d1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>e3387f34-999d-4727-b409-72e0f8ca5c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mediaCB&quot;)</value>
      <webElementGuid>3690a44e-a17c-4a62-980b-fb9a005160eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mediaCB']</value>
      <webElementGuid>612068e5-5719-4ddf-894a-915a3959b2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='confChoices']/input[2]</value>
      <webElementGuid>75c7b319-d5fd-4e10-a082-9d2f338b231d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input[2]</value>
      <webElementGuid>e36f0750-ceef-4653-8c52-d9178f8aa0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'mediaPack' and @id = 'mediaCB']</value>
      <webElementGuid>239d7a51-d6ce-4b39-b30e-9a010b79656e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
