<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_215.00</name>
   <tag></tag>
   <elementGuidId>8594327d-6432-4c9c-8eb6-295fe2cf1c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='regTotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#regTotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$215.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b55123c8-f35e-434f-b321-1f9c417e75d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regTotal</value>
      <webElementGuid>1072b80a-c78f-4c3a-90c0-18147a98987e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$215.00</value>
      <webElementGuid>94604b47-62e2-4e96-9749-82301eee9eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regTotal&quot;)</value>
      <webElementGuid>648bedcb-f1a7-4b70-b038-36b9e56475a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='regTotal']</value>
      <webElementGuid>ff9be134-e523-4258-b797-57ac9c1e5185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='reg1Aside']/table/tbody/tr[6]/td/span</value>
      <webElementGuid>19b5d8d3-67ff-4914-b73b-afded5b3c803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/following::span[1]</value>
      <webElementGuid>cd68ee4b-78c5-4fe2-a0ac-4bd0265c52c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='yes'])[1]/following::span[1]</value>
      <webElementGuid>aafdc617-15f4-4dac-a917-5bff9a96e82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$215.00']/parent::*</value>
      <webElementGuid>d6548e63-cef4-45e5-ae10-3e2b69f6ae22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/span</value>
      <webElementGuid>a9dcc596-daec-4fe3-9ea2-ae70f84b7fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'regTotal' and (text() = '$215.00' or . = '$215.00')]</value>
      <webElementGuid>1e5692a8-f8e4-4cc1-a452-347494b5b980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
