<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VSLive Banquet (80 ea.)_banquetGuests</name>
   <tag></tag>
   <elementGuidId>3ffbbe5a-0cf7-46a8-a81e-5245b8574049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#banquetBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='banquetBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#banquetBox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0180da04-90fc-4088-bb3b-297acff02c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>94e26d7d-b87d-457e-91d9-2d49cd7e9cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b996d1f-0ff7-40f1-aa86-2fbd4315d0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>653c1457-afcc-4302-ae9f-b577dd8476fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>banquetBox</value>
      <webElementGuid>14101f60-48c1-41fd-9a22-eff92712d19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>banquetGuests</value>
      <webElementGuid>78c2b757-0913-437a-9f4a-c56a50d6cf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banquetBox&quot;)</value>
      <webElementGuid>2b6b140c-404a-458d-841b-49d84c562483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='banquetBox']</value>
      <webElementGuid>463f52e5-b574-4253-bfd7-adf512599e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='confChoices']/input</value>
      <webElementGuid>efa451ef-7066-4083-8608-36d09bc3bb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input</value>
      <webElementGuid>b73dda84-2338-4a65-9f2d-ca7e00f336c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'banquetBox' and @name = 'banquetGuests']</value>
      <webElementGuid>5f6d78bb-7909-4ec7-9237-4f5bf4edf4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
