<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_expDate</name>
   <tag></tag>
   <elementGuidId>cd6a1525-3dcf-499a-a91e-643002d0293a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;mm/yyyy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4e50264-5bc6-450d-adba-f4e4e71a68c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>825c75bd-f69b-4bd2-bee5-1f24030010e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>89995d22-4353-40bf-b2b6-cac8a6bfcd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>300eb1be-370b-4127-b8c0-b4a28f83b925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/yyyy</value>
      <webElementGuid>aa47ef6a-93c7-4c30-9863-1099ae037a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expDate&quot;)</value>
      <webElementGuid>94a713b9-c418-471f-9810-dcc8376899fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expDate']</value>
      <webElementGuid>4b944458-ad81-4082-ae65-cbe5e34c64a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input[3]</value>
      <webElementGuid>06e17f43-80df-441b-9c3e-ff7b1405d8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>c0a0a9eb-786c-4a2e-aba4-18baf326c652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'expDate' and @id = 'expDate' and @type = 'text' and @placeholder = 'mm/yyyy']</value>
      <webElementGuid>d72d22ad-f4eb-439a-984f-fbed520264d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
