<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Holder_cardHolder</name>
   <tag></tag>
   <elementGuidId>bb8d1556-e33b-4f79-960a-b691c73251ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardHolder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardHolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Card Holder*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67720e8f-e3f7-4a11-82d0-9f7b1cd675ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>c0875562-fb58-4588-a376-a4837fb76b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>e5ecd999-9b48-4d4d-b172-230fa4c9214c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dff6f426-145a-4951-863f-0126d0ec06d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardHolder&quot;)</value>
      <webElementGuid>f7844a84-a976-4e0b-b69a-7c0b5c017e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardHolder']</value>
      <webElementGuid>0ed5502a-3c30-41f0-b684-b493f2ac1d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input</value>
      <webElementGuid>12732294-497c-4cf2-a3b2-3cda4999a4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e6c89397-b769-40d9-a747-6e9df7acd213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardHolder' and @id = 'cardHolder' and @type = 'text']</value>
      <webElementGuid>057215a0-9a6b-4e38-84b2-0dfcedf2b4d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
