<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CVC_cvc</name>
   <tag></tag>
   <elementGuidId>a12e7454-b0e6-47ca-9d1e-a671d217ff10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cvc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cvc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;CVC*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f349aa2b-a014-40ab-8a9d-2990c6aaaefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>20c5892a-4dc7-4703-af10-1aea947a96fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>c3cbe5aa-f4ca-4f17-ab50-30d5d047904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\d{3,4}$</value>
      <webElementGuid>fffa7d4e-a46e-464f-96cd-5051a1a39675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9c64d38-42f7-49b3-b845-2b7e133cf056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvc&quot;)</value>
      <webElementGuid>b4d1b153-4f22-42f3-a25e-c4cc8af8273a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cvc']</value>
      <webElementGuid>fa1bbbea-90c3-44f1-bbc6-93e204a1d314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input[4]</value>
      <webElementGuid>92d47b23-fb00-4d8c-aef8-3d00553071f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>b104157d-c524-41b9-b911-b408cff9e36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cvc' and @id = 'cvc' and @type = 'text']</value>
      <webElementGuid>68892fb4-434b-4fdc-aeae-93aa3966c8de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
