<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Session</name>
   <tag></tag>
   <elementGuidId>12ab91ff-c705-4df4-bcfa-5e40b1033dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='reg2Aside']/table/tbody/tr[3]/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Session&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>1988096a-d470-4879-ba4c-92268b242b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Session</value>
      <webElementGuid>b6d041fb-c34e-4613-9038-d1ddb41c27a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg2Aside&quot;)/table[1]/tbody[1]/tr[3]/th[1]</value>
      <webElementGuid>0dd9e68e-2cf8-4890-9f90-83fea9dc8619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='reg2Aside']/table/tbody/tr[3]/th</value>
      <webElementGuid>3f6fed92-b33a-473a-aa4e-3e89aa223a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::th[1]</value>
      <webElementGuid>1b196e02-eee0-4c4d-9e23-bdb2b408d2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a a'])[1]/following::th[2]</value>
      <webElementGuid>98fa4cae-d262-4a6a-921c-30eb0e501a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exhibits Only ($95.00)'])[1]/preceding::th[1]</value>
      <webElementGuid>5cf0f548-b984-432b-90a5-2758a9cf9d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banquet Guest ($70 ea.)'])[1]/preceding::th[1]</value>
      <webElementGuid>6840b92d-6711-487e-9b33-51e2c6872fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Session']/parent::*</value>
      <webElementGuid>0eee180d-75c2-4af0-bc26-0d8e1cb9e60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th</value>
      <webElementGuid>e3e0d421-b6e1-4868-9376-2d38d8c065f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Session' or . = 'Session')]</value>
      <webElementGuid>3838af7c-8df5-4534-b723-994f5003836c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
