<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Holder_cardHolder</name>
   <tag></tag>
   <elementGuidId>bc4d6c7c-9659-449b-8b2f-d9c987bbeae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardHolder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardHolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Card Holder*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad4a66e8-fb2d-47a5-b84a-c6cff6b23602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>ea7d97a4-d70b-44f4-b3fc-cd598aaf086f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>f1d1903e-6417-4c11-8695-63394260466f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d904a2f6-bacc-4a78-b2a3-713a0ddf7e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardHolder&quot;)</value>
      <webElementGuid>18a5c763-411b-41fe-b473-2b2f1f9c2c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardHolder']</value>
      <webElementGuid>938add0e-4e3b-4e80-8466-4a94b6fbfd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input</value>
      <webElementGuid>a2465164-aa4e-4136-86f1-755d34f861b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6f255319-79a1-4eb7-9695-4bbb50f602c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardHolder' and @id = 'cardHolder' and @type = 'text']</value>
      <webElementGuid>093413e5-9f6c-4100-9f7d-515b7770934a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
