<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_expDate</name>
   <tag></tag>
   <elementGuidId>9a25a549-f011-45a7-9adb-129af3ed2913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;mm/yyyy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0a8679c-77db-41ed-a58c-50480174c41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>05229df2-a0fe-4497-9579-478b359f8b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expDate</value>
      <webElementGuid>456a80ef-6fe0-4c01-98dd-8c32baf37fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f28836c6-3524-4348-b571-c3a9921b8c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/yyyy</value>
      <webElementGuid>b8d9e356-a383-4c84-a58f-1c8a6868e83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expDate&quot;)</value>
      <webElementGuid>c3182626-9c12-4d47-9003-2d66a09c5583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expDate']</value>
      <webElementGuid>341ff940-758d-4499-9df9-937953b85d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input[3]</value>
      <webElementGuid>714b6fc4-f302-41bd-9fa1-6f5d7636b489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>0412bcb0-3530-42bf-abe7-40ae3dc5e826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'expDate' and @id = 'expDate' and @type = 'text' and @placeholder = 'mm/yyyy']</value>
      <webElementGuid>d441a509-72f3-43df-a86d-772407684a85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
