<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CVC_subButton</name>
   <tag></tag>
   <elementGuidId>bcd58e8f-a998-44bb-8537-a35fcf36a5a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>133402ee-0828-400e-a469-31f3711714d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77ba5105-5f8b-40b7-97b2-a341ee53be38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subButton</value>
      <webElementGuid>352754d4-1ec9-4b0d-9523-7a4da3759187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>continue</value>
      <webElementGuid>40965c11-aa7d-4f09-a93e-17bf0026002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subButton&quot;)</value>
      <webElementGuid>04225f48-5ede-4637-acf5-59bacb339031</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subButton']</value>
      <webElementGuid>317bf481-2b26-45cb-a041-c213e64e8fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credit']/input</value>
      <webElementGuid>444ac1d9-f6af-4ef1-8022-6844ee12d399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>fce57989-3589-48c5-9a0d-d79a509204b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'subButton']</value>
      <webElementGuid>6124e016-ddaf-4a3e-b362-000914706c27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
