<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VSLive Banquet (80 ea.)_banquetGuests</name>
   <tag></tag>
   <elementGuidId>decdf32f-e56d-4666-a322-c652e2cae074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='banquetBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#banquetBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#banquetBox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35b0055f-69c7-4ec8-9faf-5c53d1f71fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7a768809-b72b-4e29-9e38-d019d42dd829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f6a2c13b-bd8f-4a08-9794-47b4b89e9e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>15b23e7b-fdb1-43cc-bdfd-78e03c34ce70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>banquetBox</value>
      <webElementGuid>d3fcc11d-bc1e-4831-ba9b-ab11d0fc02ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>banquetGuests</value>
      <webElementGuid>6ee2dd3c-8f5a-4dd6-8dcf-bf7506a5ff94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banquetBox&quot;)</value>
      <webElementGuid>b71e9682-ebc5-4a52-be8e-15b26439f372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='banquetBox']</value>
      <webElementGuid>b12ea5e5-4822-4dfa-9d35-d58eed7d7e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='confChoices']/input</value>
      <webElementGuid>5ced2c4f-df49-4239-8098-5b01a4943a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input</value>
      <webElementGuid>5a571586-9fbe-4804-872a-e9ffe8b3fbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'banquetBox' and @name = 'banquetGuests']</value>
      <webElementGuid>6e53191c-4d65-4ca8-9ebe-38a33b32f386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
