<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_useremail</name>
   <tag></tag>
   <elementGuidId>e2202000-7449-477d-b588-55446cf87bfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#useremail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='useremail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;E-mail&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a61752dc-fa61-48ba-9730-8e760d2e8c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>useremail</value>
      <webElementGuid>368057c3-d36b-4d80-8110-d00f9b210092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>useremail</value>
      <webElementGuid>abd8acfd-9cd6-40c6-96b7-449138673b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9e0622b0-7b20-4627-933a-7464d29d5aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;useremail&quot;)</value>
      <webElementGuid>8b1ab51d-ab01-44d9-9393-4ea308c46980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='useremail']</value>
      <webElementGuid>5cd472c5-0c0c-4db2-9bd4-2b92682c829a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='contactInfo']/input</value>
      <webElementGuid>5d3c2165-0397-4389-96a5-f9b79f857f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58771469-d1e8-4414-b780-315f35286f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'useremail' and @id = 'useremail' and @type = 'email']</value>
      <webElementGuid>a904e515-defa-46fb-bbe0-8b03802ce227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
