<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Holder_cardHolder</name>
   <tag></tag>
   <elementGuidId>fc46b191-133d-428c-b839-75477de0767c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardHolder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardHolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Card Holder*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>265f3ff3-9e93-4aab-9428-921b15bd5ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>bb170dd4-7293-4572-b1f5-4c8ed3cb7170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardHolder</value>
      <webElementGuid>3580a7a8-b6fd-4351-a861-59f5d081406e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ea95e9d-f5d0-463e-885b-e929c5caf700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardHolder&quot;)</value>
      <webElementGuid>72afa6d2-25bd-4089-8634-a353bb3956a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardHolder']</value>
      <webElementGuid>09639fb0-f1e4-45cd-a058-386c1643ba0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='creditcard']/input</value>
      <webElementGuid>1c2208b7-5c21-443c-b335-d32971f7bd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a6f05586-a667-4641-a8d8-f4b446779a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardHolder' and @id = 'cardHolder' and @type = 'text']</value>
      <webElementGuid>e489e829-2a4f-4c09-a7d1-ac1f11e2dbac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
