<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_regSubmit</name>
   <tag></tag>
   <elementGuidId>49051cf8-81e6-4d75-8138-afe0843f6c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#regSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='regSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>018bde34-8fb5-4fa3-ab89-325907fa9492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regSubmit</value>
      <webElementGuid>db296fa5-c67a-488f-a603-ed1b17a3023a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6328d7a6-f64b-4e30-b37d-72ea00d5fded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>continue</value>
      <webElementGuid>96a54bc0-751d-40b4-a92f-f0dcf99bcac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regSubmit&quot;)</value>
      <webElementGuid>8394b765-6d6f-4880-a8cf-7110b5d8d218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='regSubmit']</value>
      <webElementGuid>39aad20f-e68e-4c4c-851e-05f62f3d1850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='regForm']/input</value>
      <webElementGuid>669c3aef-1ddd-4c05-b7a4-4cea2895ffaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>e9193a11-1a3e-4ed2-afa5-8e749756050d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'regSubmit' and @type = 'submit']</value>
      <webElementGuid>711d8a9b-98e6-42ad-ac75-4ef99980903c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
