<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_email</name>
   <tag></tag>
   <elementGuidId>66cde29d-6f5f-4640-9bf0-a9af15145436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mailBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mailBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;E-mail*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>059cc1d3-5776-4c2c-b408-8fc71610e58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>067e2eb3-98ee-4b60-b5bf-a9bb7fd816f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mailBox</value>
      <webElementGuid>bb7e6902-b289-4e6f-a838-58a9496b0f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0a4b4923-be3f-4e37-bae0-b3b32c6c2f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailBox&quot;)</value>
      <webElementGuid>251b3e69-5d55-478d-bff1-a9c0606ed2cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mailBox']</value>
      <webElementGuid>ac2ebe61-6d93-49bb-9975-2a0f90ae57a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='contactInfo']/input[5]</value>
      <webElementGuid>687e7c15-525b-465c-b7a0-66d9729e9dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>f3ddbca0-28b2-49bf-b5f3-2a2c54e94521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @id = 'mailBox' and @type = 'email']</value>
      <webElementGuid>562bf2ec-bb13-46d1-bd6b-64dd842eda1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
