<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Phone_phoneNumber</name>
   <tag></tag>
   <elementGuidId>5603b6b6-25cb-4582-b928-b84dec6fe082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;(nnn) nnn-nnnn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40ce3779-c6e4-4e78-8133-3b387edf6c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>ef35d1ec-2914-49db-8111-8280a6751e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneBox</value>
      <webElementGuid>6005eaed-f243-4122-96d4-003e2ab524e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>bffa58a0-0e70-42a9-90f4-30410fbd1a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(nnn) nnn-nnnn</value>
      <webElementGuid>6388c3a7-1dd2-43af-a8a3-ddfec5a739a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneBox&quot;)</value>
      <webElementGuid>d5863719-5108-47fb-8afa-21fd2d891351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneBox']</value>
      <webElementGuid>22a4d5ca-88e5-49d4-9ac7-6b9c2790f155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='contactInfo']/input[6]</value>
      <webElementGuid>b39daf51-9bbc-4d57-9961-22e0f879a052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>24fbacc5-1146-4f0b-82cb-a469c9d3dfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phoneNumber' and @id = 'phoneBox' and @type = 'tel' and @placeholder = '(nnn) nnn-nnnn']</value>
      <webElementGuid>e5d14f23-cfdb-48e8-863c-35cbfb44a604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
