<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_company</name>
   <tag></tag>
   <elementGuidId>94600b00-bd2f-43c3-b083-84ae4d6e4470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='regGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#regGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;company&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73a14289-a7a8-4fdc-9adc-2bbb4830bb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regGroup</value>
      <webElementGuid>118a3545-8a3b-4f82-a94e-3417313537b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>f69b3598-7a06-4613-8d35-5f0494665453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regGroup&quot;)</value>
      <webElementGuid>90ef5d84-2785-4bd2-a432-9f4a4963c089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='regGroup']</value>
      <webElementGuid>d2cee0e7-6c48-4968-b240-f5539b543532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='reg1Aside']/table/tbody/tr[2]/td/span</value>
      <webElementGuid>a3c64c60-c46c-4fd5-bd73-74bb5e9f6596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[2]/following::span[1]</value>
      <webElementGuid>939c4acb-420d-47ec-a09e-de1bcc4ca6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='first last'])[1]/following::span[1]</value>
      <webElementGuid>291e0845-53ca-4798-8859-e5a8d4535380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Session'])[1]/preceding::span[1]</value>
      <webElementGuid>9de16583-2dd9-4d01-bea8-e9da4419f88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exhibits Only ($95.00)'])[2]/preceding::span[1]</value>
      <webElementGuid>5bdf9a45-26eb-4a51-ad19-51fcd876a7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='company']/parent::*</value>
      <webElementGuid>89538f7a-c6bf-4aa7-9e9a-2c469327a6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span</value>
      <webElementGuid>0b069262-eb1d-48f5-9af1-f43ca44b094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'regGroup' and (text() = 'company' or . = 'company')]</value>
      <webElementGuid>5d8a26b5-acbe-4c76-b99d-81c9dacb4b02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
